# Generated by Django 4.0.2 on 2022-02-21 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='studentID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionNumber', models.CharField(max_length=50)),
                ('tdifdSimilarity', models.CharField(max_length=50)),
                ('vectorSimilarity', models.CharField(max_length=50)),
                ('keywordSimilarity', models.CharField(max_length=50)),
                ('GrammerSimilarity', models.CharField(max_length=50)),
                ('finalResult', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Testno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testno', models.IntegerField(default=0)),
                ('TestName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherNumber', models.IntegerField(default=0)),
                ('teacherName', models.CharField(max_length=100)),
                ('subjectName', models.CharField(max_length=100)),
                ('testno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VbadApp.testno')),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionNumber', models.CharField(max_length=50)),
                ('tdifdSimilarity', models.CharField(max_length=50)),
                ('vectorSimilarity', models.CharField(max_length=50)),
                ('keywordSimilarity', models.CharField(max_length=50)),
                ('GrammerSimilarity', models.CharField(max_length=50)),
                ('finalResult', models.CharField(max_length=10)),
                ('studentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VbadApp.student')),
                ('teacherNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VbadApp.teacher')),
                ('testno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VbadApp.testno')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.TextField()),
                ('keyword', models.CharField(max_length=1000)),
                ('teacherNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VbadApp.teacher')),
                ('testno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VbadApp.testno')),
            ],
        ),
    ]
