# Generated by Django 4.0.2 on 2022-02-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testno', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testNumber', models.SmallIntegerField()),
                ('questionNumber', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='studentID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionNumber', models.CharField(max_length=50)),
                ('tdifdSimilarity', models.CharField(max_length=50)),
                ('vectorSimilarity', models.CharField(max_length=50)),
                ('keywordSimilarity', models.CharField(max_length=50)),
                ('GrammerSimilarity', models.CharField(max_length=50)),
                ('finalResult', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
                ('keyword', models.CharField(max_length=1000)),
                ('questionNo', models.IntegerField(default=0)),
            ],
        ),
    ]
