# Generated by Django 4.0.2 on 2022-02-11 16:56

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VbadApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='testNo',
            field=models.ForeignKey(default=0, on_delete=builtins.callable, to='VbadApp.notest'),
        ),
    ]
