# Generated by Django 4.0.2 on 2022-02-11 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VbadApp', '0002_teacher_testno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='testNo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='VbadApp.notest'),
        ),
    ]
