# Generated by Django 4.0.2 on 2022-02-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VbadApp', '0003_alter_teacher_testno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='testNo',
            new_name='testno',
        ),
    ]
