# Generated by Django 4.0.2 on 2022-02-12 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VbadApp', '0004_rename_testno_teacher_testno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='testno',
            new_name='testNo',
        ),
    ]
