# Generated by Django 4.0.2 on 2022-02-12 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VbadApp', '0006_rename_testno_teacher_testno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='testno',
            new_name='referring_testno',
        ),
    ]
