# Generated by Django 4.0.2 on 2022-02-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VbadApp', '0007_rename_testno_teacher_referring_testno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='referring_testno',
            field=models.IntegerField(default=0),
        ),
    ]
